nve_md:
  test_data: null
  calculator_params:
    num_steps: 10000
    timestep: 1.0
    temperature: 300
phonon_mdr:
  test_data: /bohr/lambench-phonon-y7vk/v1/MDR_PBE_phonon
  calculator_params:
    distance: 0.01
inference_efficiency:
  test_data: /bohr/batch-infer-7ipn/v1/batch_infer_confs
  calculator_params:
    warmup_ratio: 0.2
