# This is the configuration file for the models used in the benchmark.
# Moidifications to this file will trigger automatic workflow runs to update the benchmark results.

DP_2024Q4:
  model_name: dpa2_241126_v2_4_0
  model_type: DP
  model_path: /bohr/lambench-model-55c1/v2/dpa2_241126_v2_4_0/dp_dpa2_v2.4.0_1126_800w.pt
  virtualenv: dp_0103_prob_scp_e1a
MACE_MP_0:
  model_name: mace_mp_0_medium
  model_type: ASE
  model_path: null
  virtualenv: mace_v1.0.0
ORB_V2:
  model_name: orb_v2
  model_type: ASE
  model_path: null
  virtualenv: orb_v2
SEVENNET_0:
  model_name: 7net_0
  model_type: ASE
  model_path: null
  virtualenv: sevennet_v0.1.0
EQ_V2:
  model_name: eqV2_153M_omat_mp_salex
  model_type: ASE
  model_path: lambench/models/ASE/eq_v2/eqV2_153M_omat_mp_salex.pt
  virtualenv: eq_v2
MATTERSIM_V1_5M:
  model_name: MatterSim_v1.0.0_5M
  model_type: ASE
  model_path: lambench/models/ASE/mattersim_v1_5M/mattersim_v1_5M.pt
  virtualenv: mattersim_v1
