# This is the configuration file for the models used in the benchmark. 
# Moidifications to this file will trigger automatic workflow runs to update the benchmark results.

DP_test_v1:
  model_id: dp_demo_20241212_v1
  model_type: DP
  model_path: lambench/models/DP_test_v1
  virtualenv: dp_v3.0.0b4
  model_metadata:
      model_description: "A simple DP model for testing purposes."
MACE_test_v1:
  model_id: mace_demo_20241212_v1
  model_type: ASE
  model_path: lambench/models/MACE_test_v1
  virtualenv: mace_v1.0.0
  model_metadata:
      model_description: "A simple MACE model for testing purposes."
