# Please see Readme on how to add new models
- model_name: dpa2_241126_v2_4_0
  model_type: DP
  model_family: DP
  model_path: /bohr/lambench-model-55c1/v3/dpa2_241126_v2_4_0/dp_dpa2_v2.4.0_1126_800w.pt
  virtualenv: dp_0103_prob_scp_e1a
  model_metadata:
    model_description: "DP 2024 Q4, 37head share fitting 120GPU pretrain"
  show_finetune_task: True

- model_name: mace_mp_0_medium
  model_type: ASE
  model_family: MACE
  virtualenv: mace
  model_metadata:
    model_description: https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0/2023-12-03-mace-128-L1_epoch-199.model

- model_name: orb_v2
  model_type: ASE
  model_family: ORB
  virtualenv: orb
  model_metadata:
    model_description: https://orbitalmaterials-public-models.s3.us-west-1.amazonaws.com/forcefields/orb-v2-20241011.ckpt

- model_name: 7net_0
  model_type: ASE
  model_family: SevenNet
  virtualenv: sevennet
  model_metadata:
    model_description: https://github.com/MDIL-SNU/SevenNet/blob/main/sevenn/pretrained_potentials/SevenNet_0__11Jul2024/checkpoint_sevennet_0.pth

- model_name: eqV2_153M_omat_mp_salex
  model_type: ASE
  model_family: EquiformerV2
  model_path: /bohr/lambench-model-55c1/v3/eqV2_153M_omat_mp_salex/eqV2_153M_omat_mp_salex.pt
  virtualenv: eqv2
  model_metadata:
    model_description: "eqV2_153M_omat_mp_salex"

- model_name: MatterSim_v1.0.0_5M
  model_type: ASE
  model_family: MatterSim
  model_path: lambench/models/ASE/mattersim_v1_5M/mattersim_v1_5M.pt
  virtualenv: mattersim
  model_metadata:
    model_description: "mattersim_v1_5M"
