name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip

    - name: Install dependencies
      run: |
        pip install .[test,deepmd]

    - name: Validate YAML config files
      run: |
        python workflows/validate_configs.py
    - name: Run tests
      run: |
        python -m pytest test -vv
